version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - ${GLOBAL_NETWORK:-kafka}
    restart: unless-stopped